name             'qubit-bamboo'
maintainer       'Criteo'
maintainer_email 'r.hanna@criteo.com'
license          'Apache 2.0'
description      'Installs/Configures qubit-bamboo'
long_description 'Installs/Configures qubit-bamboo'
version          '0.1.0'
supports         'centos'

depends          'yum-epel'
