name             'qubit-bamboo'
maintainer       'Criteo'
maintainer_email 'r.hanna@criteo.com'
license          'Apache 2.0'
description      'Installs/Configures qubit-bamboo'
long_description 'Installs/Configures qubit-bamboo'
issues_url       'https://github.com/criteo-cookbooks/qubit-bamboo.git'
source_url       'https://github.com/criteo-cookbooks/qubit-bamboo.git'
version          '0.3.2'
supports         'centos'

depends          'yum-epel'
depends          'poise-service'
